from .node import (
    NODE_CLASS_MAPPINGS as _OPENROUTER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _OPENROUTER_DISPLAY_NAME_MAPPINGS,
)
from .layout_json_validator_node import (
    NODE_CLASS_MAPPINGS as _LAYOUT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LAYOUT_DISPLAY_NAME_MAPPINGS,
)
from .is_blank_node import (
    NODE_CLASS_MAPPINGS as _IS_BLANK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _IS_BLANK_DISPLAY_NAME_MAPPINGS,
)
from .desow_plan_node import (
    NODE_CLASS_MAPPINGS as _PLAN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _PLAN_DISPLAY_NAME_MAPPINGS,
)
from .desow_plan_furnish_node import (
    NODE_CLASS_MAPPINGS as _FURNISH_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _FURNISH_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **_OPENROUTER_CLASS_MAPPINGS,
    **_LAYOUT_CLASS_MAPPINGS,
    **_IS_BLANK_CLASS_MAPPINGS,
    **_PLAN_CLASS_MAPPINGS,
    **_FURNISH_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_OPENROUTER_DISPLAY_NAME_MAPPINGS,
    **_LAYOUT_DISPLAY_NAME_MAPPINGS,
    **_IS_BLANK_DISPLAY_NAME_MAPPINGS,
    **_PLAN_DISPLAY_NAME_MAPPINGS,
    **_FURNISH_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
